import type { Team } from "@/components/battle/team-panel"

export const BLUE_TEAM: Team = {
  name: "Blue Lock Strikers",
  tagline: "Seed A · 5-match win streak",
  accent: "neon",
  seed: "A",
  roundScore: 2,
  matchupElo: 2847,
  players: [
    {
      handle: "tonystark",
      role: "CAPTAIN",
      rank: "Diamond II",
      lp: 2847,
      tests: { passed: 6, total: 8 },
      submissions: 2,
      attempts: 3,
      wpm: 74,
      accuracy: 88,
      status: "compiling",
      initial: "t",
    },
    {
      handle: "nightowl",
      role: "STRIKER",
      rank: "Platinum I",
      lp: 2233,
      tests: { passed: 8, total: 8 },
      submissions: 3,
      attempts: 2,
      wpm: 92,
      accuracy: 95,
      status: "passed",
      initial: "n",
    },
  ],
}

export const RED_TEAM: Team = {
  name: "Ego Crushers",
  tagline: "Seed C · Promotion hunt",
  accent: "ember",
  seed: "C",
  roundScore: 1,
  matchupElo: 2901,
  players: [
    {
      handle: "isagi_y",
      role: "CAPTAIN",
      rank: "Diamond I",
      lp: 2901,
      tests: { passed: 5, total: 8 },
      submissions: 1,
      attempts: 1,
      wpm: 81,
      accuracy: 91,
      status: "typing",
      initial: "i",
    },
    {
      handle: "bachira",
      role: "STRIKER",
      rank: "Diamond III",
      lp: 2611,
      tests: { passed: 4, total: 8 },
      submissions: 2,
      attempts: 2,
      wpm: 78,
      accuracy: 84,
      status: "debugging",
      initial: "b",
    },
  ],
}
