export type Difficulty =
  | "Apprentice" // easy
  | "Adept" // medium
  | "Master" // hard
  | "Grandmaster" // insane
  | "Legendary" // mythic

export type Domain =
  | "DSA"
  | "System Design"
  | "Concurrency"
  | "Database"
  | "Machine Learning"
  | "Security"
  | "Distributed"
  | "Compilers"
  | "Graphics"
  | "Operating Systems"

export type ArenaSort =
  | "recommended"
  | "newest"
  | "popular"
  | "difficulty-asc"
  | "difficulty-desc"
  | "shortest"
  | "highest-xp"

export type ArenaStatus = "unattempted" | "attempted" | "solved" | "ALL"

export type ProblemStatus = "unattempted" | "attempted" | "solved"

export type Problem = {
  id: string
  code: string // e.g. "CHX-001"
  title: string
  tagline: string
  description: string
  difficulty: Difficulty
  domain: Domain
  tags: string[]
  estimatedMinutes: number
  xp: number
  acceptanceRate: number // 0–100
  solvedCount: number
  attempts: number
  status: ProblemStatus
  progress?: number // 0–1 if attempted
  isPremium: boolean
  isNew: boolean
  isHot: boolean
  isFeatured: boolean
  isDaily?: boolean
  companies: string[]
  author: string
  rating: number // 1-5 stars
  bookmarked: boolean
}

export const DIFFICULTIES: Difficulty[] = [
  "Apprentice",
  "Adept",
  "Master",
  "Grandmaster",
  "Legendary",
]

export const DOMAINS: Domain[] = [
  "DSA",
  "System Design",
  "Concurrency",
  "Database",
  "Machine Learning",
  "Security",
  "Distributed",
  "Compilers",
  "Graphics",
  "Operating Systems",
]

export const ARENA_SORTS: { id: ArenaSort; label: string }[] = [
  { id: "recommended", label: "Recommended" },
  { id: "newest", label: "Newest" },
  { id: "popular", label: "Most Solved" },
  { id: "difficulty-asc", label: "Easy → Hard" },
  { id: "difficulty-desc", label: "Hard → Easy" },
  { id: "shortest", label: "Shortest Time" },
  { id: "highest-xp", label: "Highest XP" },
]

export const ALL_TAGS: string[] = [
  "Arrays",
  "Strings",
  "Hash Map",
  "Two Pointers",
  "Sliding Window",
  "Binary Search",
  "Stack",
  "Queue",
  "Heap",
  "Linked List",
  "Trees",
  "Tries",
  "Graphs",
  "DFS",
  "BFS",
  "Topological Sort",
  "Union Find",
  "Dynamic Programming",
  "Bitmask DP",
  "Greedy",
  "Backtracking",
  "Recursion",
  "Math",
  "Geometry",
  "Number Theory",
  "Bit Manipulation",
  "Segment Tree",
  "Fenwick Tree",
  "KMP",
  "Suffix Array",
  "Sharding",
  "Caching",
  "Load Balancing",
  "Consensus",
  "CAP",
  "Sagas",
  "Event Sourcing",
  "Indexing",
  "ACID",
  "Sharded SQL",
  "Vector DB",
  "Mutexes",
  "Lock-Free",
  "Actors",
  "Async I/O",
  "Schedulers",
  "Transformers",
  "Embeddings",
  "Quantization",
  "Reinforcement",
  "Crypto",
  "Zero-Knowledge",
  "Buffer Overflow",
  "Side Channel",
  "Lexer",
  "Parser",
  "Optimization Pass",
  "Garbage Collector",
  "Ray Tracing",
  "Shaders",
  "Memory Mgmt",
  "Page Tables",
]

export const DIFFICULTY_META: Record<
  Difficulty,
  {
    label: string
    short: string
    accent: "neon" | "electric" | "ember" | "blood" | "gold"
    rank: number // for sorting
  }
> = {
  Apprentice: { label: "Apprentice", short: "I", accent: "neon", rank: 1 },
  Adept: { label: "Adept", short: "II", accent: "electric", rank: 2 },
  Master: { label: "Master", short: "III", accent: "ember", rank: 3 },
  Grandmaster: { label: "Grandmaster", short: "IV", accent: "blood", rank: 4 },
  Legendary: { label: "Legendary", short: "V", accent: "gold", rank: 5 },
}

export const DOMAIN_META: Record<
  Domain,
  { abbr: string; accent: "neon" | "electric" | "ember" | "blood" | "gold" }
> = {
  DSA: { abbr: "DSA", accent: "neon" },
  "System Design": { abbr: "SYS", accent: "electric" },
  Concurrency: { abbr: "CNC", accent: "ember" },
  Database: { abbr: "DB", accent: "gold" },
  "Machine Learning": { abbr: "ML", accent: "blood" },
  Security: { abbr: "SEC", accent: "ember" },
  Distributed: { abbr: "DIST", accent: "electric" },
  Compilers: { abbr: "CMP", accent: "neon" },
  Graphics: { abbr: "GFX", accent: "gold" },
  "Operating Systems": { abbr: "OS", accent: "blood" },
}

export const PLAYER_STATS = {
  rank: 1247,
  xp: 18420,
  weeklyXp: 1280,
  solved: 187,
  totalProblems: 642,
  streak: 14,
  legendaryUnlocked: 3,
  weeklyTarget: 5,
  weeklyDone: 3,
}

// ============== SEED DATA ==============

export const PROBLEMS: Problem[] = [
  {
    id: "p001",
    code: "CHX-001",
    title: "Median of Two Sorted Streams",
    tagline: "Maintain a running median across two infinite sorted streams in O(log n).",
    description:
      "Given two sorted streams of integers arriving asynchronously, design a data structure that returns the running median of all values seen so far. Solve under 30M ops/sec on a single thread without sacrificing correctness under skew.",
    difficulty: "Master",
    domain: "DSA",
    tags: ["Heap", "Two Pointers", "Binary Search"],
    estimatedMinutes: 55,
    xp: 480,
    acceptanceRate: 31,
    solvedCount: 4280,
    attempts: 13900,
    status: "attempted",
    progress: 0.6,
    isPremium: false,
    isNew: false,
    isHot: true,
    isFeatured: false,
    companies: ["Google", "Two Sigma", "Citadel"],
    author: "kuon.titan",
    rating: 4.8,
    bookmarked: true,
  },
  {
    id: "p002",
    code: "CHX-002",
    title: "Distributed Rate Limiter — Global Token Bucket",
    tagline: "Build a fault-tolerant 1M req/s limiter across 200 edge nodes.",
    description:
      "Design a multi-region token bucket that handles 1M req/s with <5ms latency at p99. Reason about clock drift, gossip protocols, and split-brain. Implement leader election fallback and explain the CAP trade-off you choose.",
    difficulty: "Grandmaster",
    domain: "System Design",
    tags: ["Sharding", "Caching", "Consensus", "CAP"],
    estimatedMinutes: 90,
    xp: 920,
    acceptanceRate: 18,
    solvedCount: 1140,
    attempts: 7320,
    status: "unattempted",
    isPremium: true,
    isNew: true,
    isHot: true,
    isFeatured: true,
    isDaily: true,
    companies: ["Stripe", "Cloudflare", "Discord"],
    author: "atlas.sys",
    rating: 4.9,
    bookmarked: false,
  },
  {
    id: "p003",
    code: "CHX-003",
    title: "Lock-Free MPMC Ring Buffer",
    tagline: "Wait-free producer/consumer queue with ABA-safe pointer swapping.",
    description:
      "Implement a multi-producer multi-consumer ring buffer using only atomic primitives. Avoid the ABA problem with tagged pointers, and prove your memory ordering on weakly-ordered architectures (ARM, RISC-V).",
    difficulty: "Grandmaster",
    domain: "Concurrency",
    tags: ["Lock-Free", "Mutexes", "Async I/O"],
    estimatedMinutes: 75,
    xp: 880,
    acceptanceRate: 14,
    solvedCount: 622,
    attempts: 4810,
    status: "unattempted",
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: true,
    companies: ["NVIDIA", "Meta", "Jane Street"],
    author: "vex.atomic",
    rating: 4.7,
    bookmarked: false,
  },
  {
    id: "p004",
    code: "CHX-004",
    title: "Sharded Time-Series Index",
    tagline: "Range queries over 10B rows in <50ms across 32 shards.",
    description:
      "Design an inverted time-series index that supports range queries, downsampling, and tag-based filtering. Discuss compression (Gorilla / Delta-of-Delta), shard rebalancing, and tail-latency mitigation.",
    difficulty: "Master",
    domain: "Database",
    tags: ["Indexing", "Sharded SQL", "ACID"],
    estimatedMinutes: 60,
    xp: 540,
    acceptanceRate: 27,
    solvedCount: 2110,
    attempts: 9120,
    status: "solved",
    progress: 1,
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Datadog", "Snowflake", "InfluxDB"],
    author: "halcyon.db",
    rating: 4.6,
    bookmarked: true,
  },
  {
    id: "p005",
    code: "CHX-005",
    title: "Self-Attention From Scratch",
    tagline: "Implement a 4-head transformer block — no libraries.",
    description:
      "Write a single transformer block in pure NumPy. Q/K/V projections, scaled dot-product attention with masking, multi-head reshape, residual + layer norm. Verify against a reference forward pass.",
    difficulty: "Master",
    domain: "Machine Learning",
    tags: ["Transformers", "Embeddings", "Math"],
    estimatedMinutes: 50,
    xp: 520,
    acceptanceRate: 24,
    solvedCount: 3320,
    attempts: 14080,
    status: "unattempted",
    isPremium: false,
    isNew: true,
    isHot: true,
    isFeatured: false,
    companies: ["OpenAI", "Anthropic", "Google DeepMind"],
    author: "mira.attention",
    rating: 4.9,
    bookmarked: false,
  },
  {
    id: "p006",
    code: "CHX-006",
    title: "Smallest Enclosing Circle",
    tagline: "Welzl's algorithm in expected O(n).",
    description:
      "Given n points in 2D, find the smallest enclosing circle. Implement Welzl's recursive method with random shuffling for expected linear time. Defend against degenerate collinear inputs.",
    difficulty: "Master",
    domain: "DSA",
    tags: ["Geometry", "Recursion", "Math"],
    estimatedMinutes: 45,
    xp: 460,
    acceptanceRate: 26,
    solvedCount: 1850,
    attempts: 7100,
    status: "unattempted",
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Meta", "Uber", "Tesla"],
    author: "kuon.titan",
    rating: 4.5,
    bookmarked: false,
  },
  {
    id: "p007",
    code: "CHX-007",
    title: "Zero-Knowledge Proof of Set Membership",
    tagline: "Prove x ∈ S without revealing x or |S|.",
    description:
      "Implement a Merkle-tree based ZK proof of set membership. Commit to a set of 1M elements; produce a proof for an element using Pedersen commitments. Walk through soundness and completeness.",
    difficulty: "Legendary",
    domain: "Security",
    tags: ["Zero-Knowledge", "Crypto", "Math"],
    estimatedMinutes: 110,
    xp: 1240,
    acceptanceRate: 9,
    solvedCount: 184,
    attempts: 2080,
    status: "unattempted",
    isPremium: true,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["StarkWare", "Coinbase", "Ethereum Foundation"],
    author: "noctis.zk",
    rating: 4.8,
    bookmarked: false,
  },
  {
    id: "p008",
    code: "CHX-008",
    title: "Raft, From the Wire Up",
    tagline: "Implement leader election and log replication for 5 nodes.",
    description:
      "Build a Raft cluster from scratch. Handle election timeouts, term progression, log conflicts, and snapshot installation. Pass a chaos suite that drops 30% of packets and reorders messages.",
    difficulty: "Grandmaster",
    domain: "Distributed",
    tags: ["Consensus", "CAP", "Sagas"],
    estimatedMinutes: 120,
    xp: 1080,
    acceptanceRate: 12,
    solvedCount: 410,
    attempts: 3120,
    status: "attempted",
    progress: 0.25,
    isPremium: false,
    isNew: true,
    isHot: true,
    isFeatured: false,
    companies: ["CockroachDB", "etcd", "Vercel"],
    author: "atlas.sys",
    rating: 4.9,
    bookmarked: true,
  },
  {
    id: "p009",
    code: "CHX-009",
    title: "Tiny Lisp Compiler → x86-64",
    tagline: "Write a compiler that emits NASM-compatible machine code.",
    description:
      "Build a 4-pass compiler for a Lisp subset: lexer, parser, IR generator, x86-64 emitter. Support tail-call optimization and a basic register allocator using graph coloring.",
    difficulty: "Legendary",
    domain: "Compilers",
    tags: ["Lexer", "Parser", "Optimization Pass"],
    estimatedMinutes: 240,
    xp: 1840,
    acceptanceRate: 6,
    solvedCount: 92,
    attempts: 1240,
    status: "unattempted",
    isPremium: true,
    isNew: false,
    isHot: false,
    isFeatured: true,
    companies: ["LLVM", "Apple", "Mozilla"],
    author: "nyx.compiler",
    rating: 5.0,
    bookmarked: false,
  },
  {
    id: "p010",
    code: "CHX-010",
    title: "Path Tracer in 200 Lines",
    tagline: "Render a Cornell box with global illumination.",
    description:
      "Write a CPU path tracer that supports diffuse, specular, and refractive materials. Implement importance sampling and Russian roulette termination. Render a 512×512 Cornell box in under 30 seconds.",
    difficulty: "Master",
    domain: "Graphics",
    tags: ["Ray Tracing", "Math", "Geometry"],
    estimatedMinutes: 90,
    xp: 720,
    acceptanceRate: 19,
    solvedCount: 880,
    attempts: 4620,
    status: "unattempted",
    isPremium: false,
    isNew: false,
    isHot: true,
    isFeatured: false,
    companies: ["Pixar", "NVIDIA", "Roblox"],
    author: "lumen.gfx",
    rating: 4.7,
    bookmarked: false,
  },
  {
    id: "p011",
    code: "CHX-011",
    title: "Generational GC for a Toy VM",
    tagline: "Two-space copying collector with write barriers.",
    description:
      "Implement a generational garbage collector for a stack-based VM. Add minor (young) and major (full) collection cycles with write barriers to track inter-generational pointers.",
    difficulty: "Grandmaster",
    domain: "Operating Systems",
    tags: ["Garbage Collector", "Memory Mgmt", "Schedulers"],
    estimatedMinutes: 150,
    xp: 1100,
    acceptanceRate: 11,
    solvedCount: 224,
    attempts: 2110,
    status: "unattempted",
    isPremium: true,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Oracle", "JetBrains", "Mozilla"],
    author: "vex.atomic",
    rating: 4.6,
    bookmarked: false,
  },
  {
    id: "p012",
    code: "CHX-012",
    title: "Longest Palindromic Subsequence — Bitmask",
    tagline: "Solve LPS up to n=22 with bitmask DP and rolling hashes.",
    description:
      "For very small n (≤22), compute LPS using bitmask DP. Compare to standard O(n²) DP and explain when each wins. Bonus: compress the state using Manacher's pre-pass.",
    difficulty: "Adept",
    domain: "DSA",
    tags: ["Dynamic Programming", "Bitmask DP", "Strings"],
    estimatedMinutes: 30,
    xp: 220,
    acceptanceRate: 48,
    solvedCount: 8120,
    attempts: 16800,
    status: "solved",
    progress: 1,
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Amazon", "Microsoft", "Adobe"],
    author: "ren.dp",
    rating: 4.4,
    bookmarked: false,
  },
  {
    id: "p013",
    code: "CHX-013",
    title: "Min-Cost Flow on a Bipartite Graph",
    tagline: "Successive shortest paths with potentials, Johnson-style.",
    description:
      "Solve min-cost max-flow on a bipartite assignment graph using SSP with reduced costs and Bellman-Ford initialization. Handle 5K nodes and 50K edges within 1.2 seconds.",
    difficulty: "Master",
    domain: "DSA",
    tags: ["Graphs", "Greedy", "Math"],
    estimatedMinutes: 70,
    xp: 580,
    acceptanceRate: 22,
    solvedCount: 1620,
    attempts: 7280,
    status: "unattempted",
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Two Sigma", "Hudson River Trading", "Citadel"],
    author: "ren.dp",
    rating: 4.7,
    bookmarked: true,
  },
  {
    id: "p014",
    code: "CHX-014",
    title: "Newsfeed Ranking Service",
    tagline: "Personalized top-K with sub-100ms p99 over 500M users.",
    description:
      "Architect a ranking service that ingests 200K signals/sec and serves personalized top-K feeds. Cover the candidate generator, ranker, deduper, and online-learning loop. Discuss feature stores and freshness budgets.",
    difficulty: "Master",
    domain: "System Design",
    tags: ["Sharding", "Caching", "Load Balancing", "Vector DB"],
    estimatedMinutes: 80,
    xp: 660,
    acceptanceRate: 24,
    solvedCount: 1980,
    attempts: 8240,
    status: "attempted",
    progress: 0.4,
    isPremium: false,
    isNew: true,
    isHot: true,
    isFeatured: false,
    companies: ["Meta", "TikTok", "LinkedIn"],
    author: "atlas.sys",
    rating: 4.7,
    bookmarked: true,
  },
  {
    id: "p015",
    code: "CHX-015",
    title: "Quantize a 7B LLM to int4",
    tagline: "GPTQ-style post-training quantization with <1% perplexity drift.",
    description:
      "Implement GPTQ on a 7B parameter model. Calibrate using a Wikipedia subset, recover quantization error column-wise, and verify perplexity stays within 1% of the FP16 baseline.",
    difficulty: "Grandmaster",
    domain: "Machine Learning",
    tags: ["Quantization", "Transformers", "Optimization Pass"],
    estimatedMinutes: 180,
    xp: 1320,
    acceptanceRate: 13,
    solvedCount: 312,
    attempts: 2640,
    status: "unattempted",
    isPremium: true,
    isNew: true,
    isHot: true,
    isFeatured: false,
    companies: ["Hugging Face", "Mistral AI", "NVIDIA"],
    author: "mira.attention",
    rating: 4.9,
    bookmarked: false,
  },
  {
    id: "p016",
    code: "CHX-016",
    title: "Kth Smallest in a Sorted Matrix",
    tagline: "Heap vs. binary search on the value space.",
    description:
      "Find the kth smallest element in a row- and column-sorted matrix. Compare a min-heap O(k log n) approach with binary searching on the value range. Defend the trade-off by k.",
    difficulty: "Adept",
    domain: "DSA",
    tags: ["Heap", "Binary Search", "Arrays"],
    estimatedMinutes: 25,
    xp: 180,
    acceptanceRate: 52,
    solvedCount: 9420,
    attempts: 18100,
    status: "solved",
    progress: 1,
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Google", "Apple", "Bloomberg"],
    author: "kuon.titan",
    rating: 4.3,
    bookmarked: false,
  },
  {
    id: "p017",
    code: "CHX-017",
    title: "DAG-Based Saga Orchestrator",
    tagline: "Compensating transactions across 12 microservices.",
    description:
      "Build a saga orchestrator that runs a directed acyclic graph of steps with idempotent compensations. Persist state to a write-ahead log, recover after process crash, and emit OpenTelemetry spans.",
    difficulty: "Master",
    domain: "Distributed",
    tags: ["Sagas", "Event Sourcing", "Topological Sort"],
    estimatedMinutes: 100,
    xp: 760,
    acceptanceRate: 21,
    solvedCount: 980,
    attempts: 4640,
    status: "unattempted",
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Uber", "Airbnb", "Booking.com"],
    author: "atlas.sys",
    rating: 4.6,
    bookmarked: false,
  },
  {
    id: "p018",
    code: "CHX-018",
    title: "Crack a Stripped Binary — Side Channel",
    tagline: "Recover a 16-byte AES key from cache timing.",
    description:
      "Given an AES-128 implementation that uses a T-table, recover the key from cache-timing measurements. Implement a Flush+Reload attack and reason about constant-time mitigations.",
    difficulty: "Legendary",
    domain: "Security",
    tags: ["Side Channel", "Crypto", "Buffer Overflow"],
    estimatedMinutes: 200,
    xp: 1620,
    acceptanceRate: 7,
    solvedCount: 88,
    attempts: 1410,
    status: "unattempted",
    isPremium: true,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["NSO Group", "CrowdStrike", "Trail of Bits"],
    author: "noctis.zk",
    rating: 4.9,
    bookmarked: false,
  },
  {
    id: "p019",
    code: "CHX-019",
    title: "Topological Sort of a Build Graph",
    tagline: "Detect cycles and parallelize independent build steps.",
    description:
      "Given a build graph with 50K targets, produce an execution order that maximizes parallelism. Detect cycles and report the shortest one. Bonus: support incremental rebuilds.",
    difficulty: "Adept",
    domain: "DSA",
    tags: ["Graphs", "Topological Sort", "BFS"],
    estimatedMinutes: 35,
    xp: 240,
    acceptanceRate: 44,
    solvedCount: 6120,
    attempts: 12880,
    status: "solved",
    progress: 1,
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Google", "Meta", "Bazel Team"],
    author: "ren.dp",
    rating: 4.4,
    bookmarked: false,
  },
  {
    id: "p020",
    code: "CHX-020",
    title: "Vector Search at 1B Scale",
    tagline: "HNSW index with product quantization.",
    description:
      "Build an HNSW index over 1B 768-d embeddings. Add product quantization to fit in 128 GB RAM. Hit 95% recall@10 at <10ms p99 on a single node.",
    difficulty: "Grandmaster",
    domain: "Database",
    tags: ["Vector DB", "Embeddings", "Indexing"],
    estimatedMinutes: 130,
    xp: 1180,
    acceptanceRate: 12,
    solvedCount: 248,
    attempts: 2230,
    status: "unattempted",
    isPremium: true,
    isNew: true,
    isHot: true,
    isFeatured: false,
    companies: ["Pinecone", "Weaviate", "Qdrant"],
    author: "halcyon.db",
    rating: 4.8,
    bookmarked: true,
  },
  {
    id: "p021",
    code: "CHX-021",
    title: "Word Ladder — Bidirectional BFS",
    tagline: "Shortest transformation in a 200K word dictionary.",
    description:
      "Find the shortest transformation sequence between two words. Use bidirectional BFS with a hash set. Optimize neighbor generation by indexing positional wildcards.",
    difficulty: "Apprentice",
    domain: "DSA",
    tags: ["BFS", "Hash Map", "Strings"],
    estimatedMinutes: 20,
    xp: 120,
    acceptanceRate: 64,
    solvedCount: 14200,
    attempts: 22100,
    status: "solved",
    progress: 1,
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Amazon", "Microsoft", "LinkedIn"],
    author: "kuon.titan",
    rating: 4.2,
    bookmarked: false,
  },
  {
    id: "p022",
    code: "CHX-022",
    title: "Actor-Model Chat Server — 1M Connections",
    tagline: "Erlang-style supervision with backpressure.",
    description:
      "Design a chat server that handles 1M concurrent WebSocket connections per node. Use the actor model with a supervision hierarchy. Implement per-room backpressure and graceful degradation.",
    difficulty: "Master",
    domain: "Concurrency",
    tags: ["Actors", "Async I/O", "Schedulers"],
    estimatedMinutes: 95,
    xp: 720,
    acceptanceRate: 23,
    solvedCount: 1140,
    attempts: 4860,
    status: "attempted",
    progress: 0.55,
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Discord", "WhatsApp", "Slack"],
    author: "vex.atomic",
    rating: 4.7,
    bookmarked: false,
  },
  {
    id: "p023",
    code: "CHX-023",
    title: "Suffix Array in O(n log n)",
    tagline: "DC3 / SA-IS without external libraries.",
    description:
      "Construct a suffix array of a 10M character string in under 2 seconds. Use the SA-IS algorithm. Augment with LCP array via Kasai's method for substring queries.",
    difficulty: "Grandmaster",
    domain: "DSA",
    tags: ["Suffix Array", "KMP", "Strings"],
    estimatedMinutes: 110,
    xp: 990,
    acceptanceRate: 14,
    solvedCount: 312,
    attempts: 2360,
    status: "unattempted",
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Bloomberg", "Jane Street", "Two Sigma"],
    author: "ren.dp",
    rating: 4.8,
    bookmarked: false,
  },
  {
    id: "p024",
    code: "CHX-024",
    title: "Cache-Aware Page Table Walker",
    tagline: "Implement a 4-level page walker with TLB shootdowns.",
    description:
      "Simulate a 4-level x86-64 page walker with a software TLB. Handle TLB invalidation across 32 cores when page mappings change. Measure the cost of a shootdown storm.",
    difficulty: "Grandmaster",
    domain: "Operating Systems",
    tags: ["Page Tables", "Memory Mgmt", "Mutexes"],
    estimatedMinutes: 140,
    xp: 1180,
    acceptanceRate: 10,
    solvedCount: 178,
    attempts: 1820,
    status: "unattempted",
    isPremium: true,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Intel", "AMD", "Linux Kernel"],
    author: "vex.atomic",
    rating: 4.7,
    bookmarked: false,
  },
  {
    id: "p025",
    code: "CHX-025",
    title: "RL Agent for a Sokoban Variant",
    tagline: "Train a PPO agent that solves 95% of test puzzles.",
    description:
      "Implement Proximal Policy Optimization for a 12×12 Sokoban variant with teleporters. Use a CNN-MLP policy and curriculum learning. Reach 95% solve rate on a held-out test set.",
    difficulty: "Master",
    domain: "Machine Learning",
    tags: ["Reinforcement", "Optimization Pass", "Math"],
    estimatedMinutes: 120,
    xp: 880,
    acceptanceRate: 17,
    solvedCount: 612,
    attempts: 3640,
    status: "unattempted",
    isPremium: false,
    isNew: true,
    isHot: false,
    isFeatured: false,
    companies: ["DeepMind", "OpenAI", "Anthropic"],
    author: "mira.attention",
    rating: 4.6,
    bookmarked: false,
  },
  {
    id: "p026",
    code: "CHX-026",
    title: "Two Sum — But With a Twist",
    tagline: "Find pairs summing to target across a streaming window.",
    description:
      "Given an integer stream and a sliding window of size W, find all pairs in the window summing to a target T. Maintain O(W) memory and O(1) amortized work per element.",
    difficulty: "Apprentice",
    domain: "DSA",
    tags: ["Hash Map", "Sliding Window", "Two Pointers"],
    estimatedMinutes: 15,
    xp: 90,
    acceptanceRate: 71,
    solvedCount: 22400,
    attempts: 31900,
    status: "solved",
    progress: 1,
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Amazon", "Google", "Stripe"],
    author: "ren.dp",
    rating: 4.1,
    bookmarked: false,
  },
  {
    id: "p027",
    code: "CHX-027",
    title: "Real-Time Multiplayer Lockstep",
    tagline: "Deterministic simulation across 8 clients with rollback.",
    description:
      "Implement deterministic lockstep with rollback netcode for an 8-player game. Handle input prediction, state checkpointing, and resimulation when a misprediction is detected.",
    difficulty: "Grandmaster",
    domain: "Distributed",
    tags: ["Consensus", "Async I/O", "Schedulers"],
    estimatedMinutes: 160,
    xp: 1240,
    acceptanceRate: 11,
    solvedCount: 184,
    attempts: 1920,
    status: "unattempted",
    isPremium: true,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Riot Games", "Epic Games", "Valve"],
    author: "atlas.sys",
    rating: 4.8,
    bookmarked: false,
  },
  {
    id: "p028",
    code: "CHX-028",
    title: "Trie + Aho-Corasick — Multi-Pattern Match",
    tagline: "Find 10K patterns in a 1GB log stream.",
    description:
      "Build an Aho-Corasick automaton on 10K patterns. Stream a 1GB log and report every match with its position. Hit 500MB/s throughput on a single core.",
    difficulty: "Master",
    domain: "DSA",
    tags: ["Tries", "KMP", "Strings"],
    estimatedMinutes: 60,
    xp: 540,
    acceptanceRate: 22,
    solvedCount: 1320,
    attempts: 6020,
    status: "unattempted",
    isPremium: false,
    isNew: false,
    isHot: true,
    isFeatured: false,
    companies: ["Cloudflare", "Splunk", "Elastic"],
    author: "kuon.titan",
    rating: 4.6,
    bookmarked: true,
  },
  {
    id: "p029",
    code: "CHX-029",
    title: "Segment Tree With Lazy Propagation",
    tagline: "Range update + range query in O(log n).",
    description:
      "Implement a segment tree supporting range additions and range-sum queries with lazy propagation. Handle 1M operations in under 600ms. Bonus: persistent variant.",
    difficulty: "Adept",
    domain: "DSA",
    tags: ["Segment Tree", "Fenwick Tree", "Recursion"],
    estimatedMinutes: 40,
    xp: 280,
    acceptanceRate: 39,
    solvedCount: 4820,
    attempts: 12300,
    status: "attempted",
    progress: 0.7,
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Codeforces", "Google", "Two Sigma"],
    author: "ren.dp",
    rating: 4.5,
    bookmarked: false,
  },
  {
    id: "p030",
    code: "CHX-030",
    title: "GPU Shader: Volumetric Clouds",
    tagline: "Ray-march a noise-driven volume in real time.",
    description:
      "Write a GLSL fragment shader that ray-marches volumetric clouds using layered noise. Hit 60fps at 1080p on integrated GPUs. Add Henyey-Greenstein phase scattering for sun/eye angle realism.",
    difficulty: "Master",
    domain: "Graphics",
    tags: ["Shaders", "Ray Tracing", "Math"],
    estimatedMinutes: 80,
    xp: 660,
    acceptanceRate: 19,
    solvedCount: 540,
    attempts: 2920,
    status: "unattempted",
    isPremium: false,
    isNew: true,
    isHot: false,
    isFeatured: false,
    companies: ["Unity", "Unreal", "Roblox"],
    author: "lumen.gfx",
    rating: 4.7,
    bookmarked: false,
  },
  {
    id: "p031",
    code: "CHX-031",
    title: "Distributed Snapshot — Chandy-Lamport",
    tagline: "Capture a consistent global state without stopping the world.",
    description:
      "Implement Chandy-Lamport's distributed snapshot algorithm on a 12-node ring. Verify the snapshot is causally consistent under continuous message exchange.",
    difficulty: "Master",
    domain: "Distributed",
    tags: ["Consensus", "Sagas", "Event Sourcing"],
    estimatedMinutes: 75,
    xp: 620,
    acceptanceRate: 20,
    solvedCount: 760,
    attempts: 3820,
    status: "unattempted",
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Vercel", "Confluent", "Databricks"],
    author: "atlas.sys",
    rating: 4.6,
    bookmarked: false,
  },
  {
    id: "p032",
    code: "CHX-032",
    title: "Number Theory: Pollard's Rho",
    tagline: "Factor a 64-bit semiprime in under 100ms.",
    description:
      "Implement Pollard's rho factorization with Brent's cycle detection and Miller-Rabin primality. Factor 1000 random 64-bit semiprimes in under 100s total.",
    difficulty: "Master",
    domain: "DSA",
    tags: ["Number Theory", "Math", "Bit Manipulation"],
    estimatedMinutes: 50,
    xp: 460,
    acceptanceRate: 24,
    solvedCount: 1080,
    attempts: 4480,
    status: "unattempted",
    isPremium: false,
    isNew: false,
    isHot: false,
    isFeatured: false,
    companies: ["Two Sigma", "Citadel", "Jane Street"],
    author: "kuon.titan",
    rating: 4.5,
    bookmarked: false,
  },
]

// ============== Helpers ==============

export function formatTime(min: number) {
  if (min < 60) return `${min}m`
  const h = Math.floor(min / 60)
  const m = min % 60
  return m === 0 ? `${h}h` : `${h}h ${m}m`
}

export function formatCount(n: number) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`
  return n.toString()
}

// ============== Side rail static data ==============

export const TOP_SOLVERS = [
  { rank: 1, handle: "kazu.r1n", flag: "JP", solved: 612, weekly: 38, xp: 142800 },
  { rank: 2, handle: "phantom.x", flag: "DE", solved: 588, weekly: 42, xp: 138420 },
  { rank: 3, handle: "echo.zero", flag: "US", solved: 571, weekly: 29, xp: 132100 },
  { rank: 4, handle: "veil.cipher", flag: "IN", solved: 540, weekly: 33, xp: 124800 },
  { rank: 5, handle: "axiom.koi", flag: "KR", solved: 522, weekly: 41, xp: 119240 },
]

export const SKILL_MATRIX = [
  { domain: "DSA", level: 78, color: "neon" as const },
  { domain: "System Design", level: 64, color: "electric" as const },
  { domain: "Concurrency", level: 47, color: "ember" as const },
  { domain: "Database", level: 58, color: "gold" as const },
  { domain: "Machine Learning", level: 39, color: "blood" as const },
  { domain: "Distributed", level: 51, color: "electric" as const },
]

export const RECENT_ACTIVITY = [
  { tag: "SOLVED", text: "kazu.r1n cleared CHX-009 in 1h 42m", time: "3m" },
  { tag: "WR", text: "phantom.x set new world record on CHX-002 (2:11)", time: "12m" },
  { tag: "BOSS", text: "Boss Battle CHX-018 unlocked for the top 1%", time: "27m" },
  { tag: "DROP", text: "5 new Legendary problems dropped", time: "1h" },
  { tag: "FORGE", text: "Skill Forge: DP intensive starts in 2 hours", time: "2h" },
]
